#SPDX-License-Identifier: MIT-0
galaxy_info:
  author: Semen Aleksandrov
  description: This role creates a text file with default content
  company: my company
  galaxy_name: file_create
  namespace: aleksandrov
  license: MIT

  min_ansible_version: 2.2

  galaxy_tags: []

dependencies: []

